# Generated by Django 4.2 on 2024-11-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScannnedData',
            new_name='ScannedData',
        ),
    ]
